/**THIS FILE IS AUTOGENERATED, DO NOT EDIT**/
import { IconGallery, IconItem } from '@storybook/blocks';
import { Icon } from './index';
const Gallery = () => (
  <IconGallery>
    <IconItem name="Add">
      <Icon use="add" />
    </IconItem>

    <IconItem name="AppLogo">
      <Icon use="applogo" />
    </IconItem>

    <IconItem name="Arrow">
      <Icon use="arrow" />
    </IconItem>

    <IconItem name="Chevron">
      <Icon use="chevron" />
    </IconItem>

    <IconItem name="Clipboard">
      <Icon use="clipboard" />
    </IconItem>

    <IconItem name="Close">
      <Icon use="close" />
    </IconItem>

    <IconItem name="Delete">
      <Icon use="delete" />
    </IconItem>

    <IconItem name="Denied">
      <Icon use="denied" />
    </IconItem>

    <IconItem name="Edit">
      <Icon use="edit" />
    </IconItem>

    <IconItem name="Error">
      <Icon use="error" />
    </IconItem>

    <IconItem name="Help">
      <Icon use="help" />
    </IconItem>

    <IconItem name="House">
      <Icon use="house" />
    </IconItem>

    <IconItem name="Info">
      <Icon use="info" />
    </IconItem>

    <IconItem name="Logout">
      <Icon use="logout" />
    </IconItem>

    <IconItem name="Moon">
      <Icon use="moon" />
    </IconItem>

    <IconItem name="Refresh">
      <Icon use="refresh" />
    </IconItem>

    <IconItem name="Search">
      <Icon use="search" />
    </IconItem>

    <IconItem name="Signpost">
      <Icon use="signpost" />
    </IconItem>

    <IconItem name="Success">
      <Icon use="success" />
    </IconItem>

    <IconItem name="Sun">
      <Icon use="sun" />
    </IconItem>

    <IconItem name="Tag">
      <Icon use="tag" />
    </IconItem>

    <IconItem name="Upload">
      <Icon use="upload" />
    </IconItem>

    <IconItem name="Warning">
      <Icon use="warning" />
    </IconItem>
  </IconGallery>
);
export default Gallery;
